### ISSUE TITLE
Random Segmentation Faults with Node v5.9.0

### ISSUE THREAD

**Issue by m99coder** [gruntjs/grunt-cli#97] opened 2016-03-18 17:57 UTC
I updated to Node v5.9.0 and getting random segmentation faults now. Sorry for not giving more details. I don’t have any.

**Comment by vladikoff** [comment] 2016-03-18 18:09
> getting random segmentation faults now

Even though you don't have detail it would help to know which plugins are triggering this, what OS, etc

**Comment by m99coder** [comment] 2016-03-18 18:50
It happend executing `grunt-contrib-clean` and I’m using Mac OS X 10.11.3. Not sure if it’s really an issue for grunt or maybe node itself.

**Comment by nmalaguti** [comment] 2016-03-18 21:20
Very likely the same issue as https://github.com/nodejs/node/issues/5769, which is a dupe of https://github.com/nodejs/node/issues/5768.

You can check your crash reports to get a backtrace and confirm.

**Comment by vladikoff** [comment] 2016-03-18 21:21
Thank you!

**Comment by m99coder** [comment] 2016-03-18 21:25
Ah. Thanks for the hint. Indeed it’s the node::ContextifyScript.
```
Process:               node [20273]
Path:                  /usr/local/bin/node
Identifier:            node
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        zsh [20170]
Responsible:           node [20273]
User ID:               501

Date/Time:             2016-03-18 13:36:33.058 +0100
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        97F02B21-79AA-EA29-74F6-A02716E66B86

Sleep/Wake UUID:       5ED6DF65-93EF-4819-8F71-27CAE2E89D3F

Time Awake Since Boot: 2200000 seconds
Time Since Wake:       180 seconds

System Integrity Protection: enabled

Crashed Thread:        0  grunt  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Thread 0 Crashed:: grunt  Dispatch queue: com.apple.main-thread
0   node                          	0x0000000100514385 node::ContextifyScript::RunInContext(v8::FunctionCallbackInfo<v8::Value> const&) + 311
1   node                          	0x0000000100156975 v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) + 159
2   node                          	0x0000000100177a7c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>&) + 992
3   node                          	0x0000000100179bbc v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) + 65
```

**Closed** 2016-03-18 21:53 UTC
