### ISSUE TITLE
grunt --gruntfile some/path/Gruntfile.js cannot find local grunt since grunt-cli 1.0.0

### ISSUE THREAD

**Issue by EtienneMiret** [gruntjs/grunt-cli#101] opened 2016-03-22 13:41 UTC
Since the release of grunt-cli 1.0.0, the command <kbd>grunt --gruntfile some/path/Gruntfile.js</kbd> issues the following error message :

> Fatal error: Unable to find local grunt.
>
> If you're seeing this message, grunt hasn't been installed locally to
> your project. For more information about installing and configuring grunt,
> please see the Getting Started guide:
>
> http://gruntjs.com/getting-started

Before that release, the same command would work fine.

I have my `package.json` and my `node_modules` inside the directory `some/path`, next to `Gruntfile.js`.

Using :
 - node 5.9.0
 - npm 3.7.3
 - grunt-cli 1.0.0
 - grunt 0.4.5

**Comment by vladikoff** [comment] 2016-03-22 13:46
Thanks for the report!

**Comment by vladikoff** [comment] 2016-03-22 14:02
What OS are you on? 

I cannot reproduce this issue, i made a test repo: https://github.com/vladikoff/issue-grunt-cli-101

Running `grunt --gruntfile some/Gruntfile.js` gives me

```
Running "jshint:all" (jshint) task
ERROR: Can't find config file: .jshintrc
``` 

So it can find everything. Let me know!

**Comment by vladikoff** [comment] 2016-03-22 14:03
@shama thoughts?

**Comment by EtienneMiret** [comment] 2016-03-22 14:35
Hello @vladikoff.

I'm having the issue with Travis-ci (can't link to a build though, because it is private) and with the release of Ubuntu you get with docker's [digitallyseamless/nodejs-bower-grunt:latest][1].

[1]: https://hub.docker.com/r/digitallyseamless/nodejs-bower-grunt/

**Comment by vladikoff** [comment] 2016-03-22 14:38
@EtienneMiret the dockerfile does nothing special here: https://hub.docker.com/r/digitallyseamless/nodejs-bower-grunt/~/dockerfile/

Could you try my test repo above and see if it is the same setup as your private project?

**Comment by EtienneMiret** [comment] 2016-03-22 14:51
I can reproduce the issue with your test repo:

    $ git clone https://github.com/vladikoff/issue-grunt-cli-101.git
    $ docker pull digitallyseamless/nodejs-bower-grunt:latest
    $ docker run -it -v /home/etienne/workspace/issue-grunt-cli-101:/data digitallyseamless/nodejs-bower-grunt:latest
    # npm --prefix some install
    # ls some/
    Gruntfile.js  etc  node_modules  package.json
    # grunt --gruntfile some/Gruntfile.js 
    grunt-cli: The grunt command line interface (v1.0.0)
    
    Fatal error: Unable to find local grunt.
    
    If you're seeing this message, grunt hasn't been installed locally to
    your project. For more information about installing and configuring grunt,
    please see the Getting Started guide:
    
    http://gruntjs.com/getting-started
    # cd some
    # grunt 
    Running "jshint:all" (jshint) task
    ERROR: Can't find config file: .jshintrc

**Comment by vladikoff** [comment] 2016-03-22 14:52
> I can reproduce the issue with your test repo:

Not true, see the output it actually loads the jshint task. `Running "jshint:all" (jshint) task`. By the time it throws the `Can't find config file: .jshintrc` everything is loaded.

**Comment by vladikoff** [comment] 2016-03-22 14:53
Oh wait nevermind

**Comment by vladikoff** [comment] 2016-03-22 14:53
Okay I'm checking on my Ubuntu 14 now...

**Comment by EtienneMiret** [comment] 2016-03-22 15:00
Thanks. I reproduced it on Travis, if that's of any help to you : https://travis-ci.org/EtienneMiret/issue-grunt-cli-101/builds/117728404.

**Comment by vladikoff** [comment] 2016-03-22 15:01
@EtienneMiret Ok I think I have it reproducible on Ubuntu 14 locally. thanks for testing it out...

**Comment by vladikoff** [comment] 2016-03-22 15:28
Ok the issue is the nopt update

**Comment by vladikoff** [comment] 2016-03-22 15:30
```
New:
{ gruntfile: true,
  argv: 
   { remain: [ 'some/Gruntfile.js' ],
     cooked: [ '--gruntfile', 'some/Gruntfile.js' ],
     original: [ '--gruntfile', 'some/Gruntfile.js' ] } }

Old:
{ gruntfile: 'some/Gruntfile.js',
  argv: 
   { remain: [],
     cooked: [ '--gruntfile', 'some/Gruntfile.js' ],
     original: [ '--gruntfile', 'some/Gruntfile.js' ],
     toString: [Function] } }
```

**Comment by vladikoff** [comment] 2016-03-22 15:49
@EtienneMiret your build should be fixed now via: https://github.com/gruntjs/grunt-cli/commit/190d90c3f310b384834391bc53457c964bba9587

**Closed by vladikoff** 2016-03-22 15:49 UTC

**Comment by EtienneMiret** [comment] 2016-03-22 16:23
Indeed, it is. Thanks a lot.

**Comment by shama** [comment] 2016-03-23 02:22
This behavior is expected with `grunt@1.0.0`. See the release notes regarding `nopt`: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#api-changes

The new syntax should be `grunt --gruntfile=some/path/Gruntfile.js`.

**Comment by EtienneMiret** [comment] 2016-03-23 09:21
Oh, OK. Sorry about that. I read `CHANGELOG.md` before submitting this issue, maybe you want to put a link to gruntjs.com there.

**Comment by shama** [comment] 2016-03-23 15:32
@EtienneMiret That is a good idea. We've got this specific change now listed in the changelog and will try to make this change more prominent in the upcoming release notes for `grunt@1.0.0`. Thanks!
