### ISSUE TITLE
Disable terminal color codes when not in a tty

### ISSUE THREAD

**Issue by mcandre** [gruntjs/grunt-cli#72] opened 2015-02-22 21:58 UTC
As a command line user, I want grunt-cli to disable terminal color codes when I pipe grunt commands to `less`, etc.

**Comment by jimf** [comment] 2015-04-24 17:34
Duplicate of #53.

**Comment by shama** [comment] 2016-01-29 03:17
Closing as duplicate of #53. Thanks @jimf!

**Closed by shama** 2016-01-29 03:17 UTC
